name: CI for Utilities
on: pull_request
jobs:


  job-genmut:
    runs-on: ubuntu-latest
    steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Execute validateFQ.py
         run: |
           pip install numpy
           pip install biopython
           pip install pandas
           cd ${{ github.workspace }}/utilities
           python gen_mut_model.py -r ../sample_data/ecoli.fa -m ../sample_data/small.vcf -o testgmm  
       - run: echo "🍏 This job's status is ${{ job.status }}."
