name: CI for Utilities
on: pull_request
jobs:
  Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
  job-valBAM:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Execute validateBAM.py
        run: |
          cd ${{ github.workspace }}/utilities
          python validateBam.py -i ../sample_data/baby.bam
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
  job-valFQ:
    runs-on: ubuntu-latest
    steps:
       - name: Check out repository code
         uses: actions/checkout@v2
       - name: Execute validateFQ.py
         run: |
           pip install biopython
           cd ${{ github.workspace }}/utilities
           python validateFQ.py -i ../sample_data/baby.fastq
       - run: echo "🍏 This job's status is ${{ job.status }}."
